module.exports = {
  content: [
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // Canopy frontend palette: dark neutral surfaces + neon canopy green
        canopy: {
          50:  '#f2fdf4',
          100: '#defbe3',
          200: '#bcf6c7',
          300: '#8ceb96',
          400: '#45ca46',
          500: '#35cd48',
          600: '#1dd13a',
          700: '#0fa32c',
          800: '#0c7f24',
          900: '#0c5f1e',
          950: '#0e200e',
        },
        bg: {
          primary:   '#171717',
          secondary: '#1f1f1f',
          tertiary:  '#2f2f2f',
          accent:    '#242424',
        },
        text: {
          primary:   '#ffffff',
          secondary: '#ebebeb',
          muted:     '#b3b3b3',
          accent:    '#35cd48',
        },
        status: {
          success: '#45ca46',
          warning: '#f59e0b',
          error:   '#ef4444',
          info:    '#3b82f6',
        },
        border:     'hsl(var(--border))',
        input:      'hsl(var(--input))',
        ring:       'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT:   '#35CD48',
          foreground:'#0f0f0f',
          light:     '#45CA46',
          50:  '#f2fdf4',
          100: '#defbe3',
          200: '#bcf6c7',
          300: '#8ceb96',
          400: '#45ca46',
          500: '#35CD48',
          600: '#1dd13a',
          700: '#0fa32c',
          800: '#0c7f24',
          900: '#0c5f1e',
        },
        navbar:    '#171717',
        back:      '#6B7280',
        secondary: {
          DEFAULT:   '#1f1f1f',
          foreground:'#ffffff',
        },
        destructive: {
          DEFAULT:   '#ef4444',
          foreground:'#ffffff',
        },
        muted: {
          DEFAULT:   '#242424',
          foreground:'#b3b3b3',
        },
        'input-surface': '#242424',
        accent: {
          DEFAULT:   '#35cd48',
          foreground:'#0f0f0f',
        },
        popover: {
          DEFAULT:   '#1f1f1f',
          foreground:'#ffffff',
        },
        card: {
          DEFAULT:   '#262626',
          foreground:'#ffffff',
        },
      },
      spacing: {
        '18':  '4.5rem',
        '88':  '22rem',
        '52':  '13rem',
        '220': '220px',
      },
      fontSize: {
        'xs':  ['0.6875rem', { lineHeight: '1rem'    }],
        'sm':  ['0.8125rem', { lineHeight: '1.25rem' }],
        'base':['0.9375rem', { lineHeight: '1.5rem'  }],
        'lg':  ['1.0625rem', { lineHeight: '1.75rem' }],
        'xl':  ['1.1875rem', { lineHeight: '1.75rem' }],
        '2xl': ['1.4375rem', { lineHeight: '2rem'    }],
        '3xl': ['1.8125rem', { lineHeight: '2.25rem' }],
      },
      boxShadow: {
        'wallet':    '0 4px 24px hsl(220 20% 3% / 0.6)',
        'wallet-lg': '0 12px 40px hsl(220 20% 3% / 0.7)',
        'glow':      '0 0 20px hsl(128 60% 51% / 0.18), 0 0 40px hsl(128 60% 51% / 0.08)',
        'glow-sm':   '0 0 10px hsl(128 60% 51% / 0.14)',
        'inner-top': 'inset 0 1px 0 hsl(0 0% 100% / 0.06)',
      },
      fontFamily: {
        display: ['Syne', 'sans-serif'],
        mono:    ['JetBrains Mono', 'Menlo', 'Consolas', 'monospace'],
        body:    ['Plus Jakarta Sans', 'sans-serif'],
        // keep legacy
        inter:   ['Plus Jakarta Sans', 'sans-serif'],
      },
      borderRadius: {
        'sm':  '0.25rem',
        DEFAULT: '0.5rem',
        'md':  '0.5rem',
        'lg':  '0.625rem',
        'xl':  '0.75rem',
        '2xl': '1rem',
        '3xl': '1.25rem',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to:   { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to:   { height: '0' },
        },
        'pulse-glow': {
          '0%, 100%': { boxShadow: '0 0 8px hsl(128 60% 51% / 0.1)' },
          '50%':      { boxShadow: '0 0 20px hsl(128 60% 51% / 0.3)' },
        },
        'slide-in-left': {
          from: { transform: 'translateX(-100%)' },
          to:   { transform: 'translateX(0)' },
        },
        'fade-up': {
          from: { opacity: '0', transform: 'translateY(8px)' },
          to:   { opacity: '1', transform: 'translateY(0)' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up':   'accordion-up 0.2s ease-out',
        'pulse-glow':     'pulse-glow 2.4s ease-in-out infinite',
        'slide-in-left':  'slide-in-left 0.28s ease-out',
        'fade-up':        'fade-up 0.3s ease-out',
      },
    },
    container: { center: true, padding: '2rem', screens: { '2xl': '1400px' } },
  },
  plugins: [],
  darkMode: ['class'],
};
